config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'posts#index'

  resources :posts, except: [:index] do
    resources :comments, shallow: true, only: %i[create destroy]
  end
  get '/change_password', to: 'users#change_password', as: :change_password
  post '/update_password', to: 'users#update_password', as: :update_password
  resources :users, only: %i[new create edit update]
  resource :session, only: [:new]
  resources :sessions, only: %i[create destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new

    if user.is_admin
      can :manage, :all
    else
      can :read, :all
    end

    alias_action :edit, :delete, to: :crud

    can :crud, Post do |post|
      post.user == user
    end

    can :destroy, Comment do |comment|
      comment.user == user || comment.post.user == user
    end

    can :crud, User, id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: {maximum:255}
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: {minimum:50}
end 

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
  def authenticated_user!
    redirect_to new_session_path, {alert: "Please sign in first", status: 303} unless user_signed_in?
  end
  helper_method :authenticated_user! 

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?
  
  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticated_user!
  before_action :find_comment, only: [:destroy]
  before_action :authorized_user!, only: [:destroy]

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new params.require(:comment).permit(:body)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post), status: 303
    else
      @comments = @post.comments.order(created_at: :desc)
      render 'posts/show', status: 303
    end
  rescue StandardError => e
    redirect_to root_path, { alert: e.message, status: 303 }
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@comment.post), status: 303
  rescue StandardError => e
    redirect_to root_path, { alert: e.message, status: 303 }
  end

  private

  def find_comment
    @comment = Comment.find params[:id]
  end

  def authorized_user!
    redirect_to post_path(@comment.post), { status: 303, alert: 'Not authorized' } unless can?(:destroy, @comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticated_user!, except: %i[index show]
  before_action :find_post, except: %i[index new create]
  before_action :authorized_user!, only: %i[edit update destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  rescue StandardError => e
    redirect_to root_path, {alert: e.message, status: 303}
  end

  def destroy
    @post.destroy
    redirect_to root_path, { notice: 'Post deleted successfully', status: 303 }
  rescue StandardError => e
    redirect_to root_path, {alert: e.message, status: 303}
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params.require(:post).permit(:title, :body)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post) # { status: 303, notice: 'Post created successfully' }
    else
      render :new, status: 303
    end
  end

  def edit
  rescue StandardError => e
    redirect_to root_path, {alert: e.message, status: 303}
  end

  def update
    if @post.update params.require(:post).permit(:title, :body)
      redirect_to post_path(@post), { status: 303, notice: 'Post updated successfully' }
    else
      render :edit, status: 303
    end
  rescue StandardError => e
    redirect_to root_path, {alert: e.message, status: 303}
  end

  private

  def find_post
    @post = Post.find params[:id]
  end

  def authorized_user!
    redirect_to post_path(@post), { status: 303, alert: 'Not authorized' } unless can?(:crud, @post)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by_email params[:email]
    if @user&.authenticate params[:password]
      session[:user_id]=@user.id
      redirect_to root_path, status: 303
    else
      flash.alert = "User not found"
      render :new, status: 303
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, status: 303
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticated_user!, except: %i[new create]
  before_action :find_user, only: %i[edit update]
  before_action :authorized_user!, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:name, :email, :password, :password_confirmation)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, status: 303
    else
      render :new, status: 303
    end
  end

  def edit; end

  def update
    if @user.update params.require(:user).permit(:name, :email, :password, :password_confirmation)
      redirect_to root_path, status: 303
    else
      flash.alert = 'Update failed, please try again'
      render :edit, status: 303
    end
  end

  def change_password
    @user = User.new
  end

  def update_password
    current_password = params[:current_password]
    new_password = params[:new_password]
    new_password_confirmation = params[:new_password_confirmation]
    user = User.find_by_id current_user.id
    if user&.authenticate current_password
      if new_password == current_password
        flash.alert = 'New password must be different'
        render :change_password, status: 303
      elsif new_password == new_password_confirmation
        if user.update password: new_password
          redirect_to root_path, { notice: 'Password updated', status: 303 }
        else
          flash.alert = 'Password update failed, try again'
          render :change_password, status: 303
        end
      else
        flash.alert = 'New password confirmation does not match'
        render :change_password, status: 303
      end
    else
      flash.alert = 'Current password does not match'
      render :change_password, status: 303
    end
  end

  private

  def find_user
    @user = User.find_by_id params[:id]
  end

  def authorized_user!
    redirect_to root_path, { status: 303, alert: 'Not authorized' } unless can?(:crud, @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog On Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico'%>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <div class="brand"> 
          <%= link_to 'Blog On Rails', root_path %>
        </div>
        <ul class="menu">
          <li>
            <%= link_to 'Home', root_path %>
          </li>
          <li>
            <%= link_to 'New Post', new_post_path %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to current_user.name, edit_user_path(current_user.id) %>
            </li>
            <li>
              <%= button_to 'Sign Out', session_path(current_user.id), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', new_session_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_path %>
            </li>
          <% end %>
        </ul>
      </nav> 
    </header> 
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= form_with model: @post do |form| %>
    <div class="post-form">
      <div class="input-group">
        <%= form.label :title %>
        <%= form.text_field :title %>
        <% if @post.errors.any? %>
          <p><%= @post.errors.full_messages_for(:title).join(", ") %></p>
        <% end %>
      </div>
      <div class="input-group">
        <%= form.label :body %>
        <%= form.text_area :body, size: "60x10" %>
        <% if @post.errors.any? %>
          <p><%= @post.errors.full_messages_for(:body).join(", ") %></p>
        <% end %>
      </div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
  <main class="posts">
    <% @posts.each do |post| %>
      <article class="post">
        <div class="details">
          <%= link_to post.title, post_path(post) %>
          <p><%= post.body %></p>
        </div>
      </article>
    <% end %>
  </main>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<% if @post %>
  <main class="post">
    <div class="details">
      <p class="title"><%= @post.title %></p>
      <p class="body"><%= @post.body %></p>
      <p class="date">Posted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %></p>
    </div>
    <% if can?(:crud, @post) %>
      <div class="buttons">
        <%= button_to 'Edit', edit_post_path(@post), method: :get %>
        <%= button_to 'Delete',post_path(@post), method: :delete %>
      </div>
    <% end %>
  </main>
<% end %>
 
<%= form_with model: @comment, url: post_comments_path(@post) do |form| %>
  <div class="comment-form">
    <%= form.label :body, "Comment" %>
    <%= form.text_area :body, maxlength: "255", rows: "5" %>
    <% if @comment.errors.any? %>
      <p><%= @comment.errors.full_messages.join(", ").gsub("Body", "Comment") %></p>
    <% end %>
    <%= form.submit :Submit %>
  </div>
<% end %>

<section class="comments">
  <% @comments&.each do |comment| %>
    <article class="comment">
      <p class="body"><%= comment.body %></p>
      <p class="date">Commented <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %> • <%= link_to 'Delete', comment_path(comment), data: { turbo_method: :delete } %></p>
    </article>
  <% end %>
</section>

app/views/users/change_password.html.erb
  <%= form_with url: update_password_path do |form| %>
    <div class="user-form">
      <div class="input-group">
        <%= form.label :current_password %>
        <%= form.password_field :current_password, required: :required %>
      </div>
      <div class="input-group">
        <%= form.label :new_password %>
        <%= form.password_field :new_password, required: :required %>
      </div>
      <div class="input-group">
        <%= form.label :new_password_confirmation %>
        <%= form.password_field :new_password_confirmation, required: :required  %>
      </div>
      <div class="input-group">
        <%flash.each do |type, msg| %>
          <p class="<%= type %>"><%= msg %></p>
        <% end %>
      </div>
      <%= form.submit 'Update password' %>
    </div>
  <% end %>

app/views/users/edit.html.erb
  <%= form_with model: @user do |form| %>
    <div class="user-form">
      <div class="input-group">
        <%= form.label :name %>
        <%= form.text_field :name, required: :required, minLength: 3 %>
      </div>
      <div class="input-group">
        <%= form.label :email %>
        <%= form.email_field :email, required: :required %>
        <% if @user.errors.any? %>
          <p><%= @user.errors.full_messages_for(:email).join(", ") %></p>
        <% end %>
      </div>
      <div class="input-group">
        <%flash.each do |type, msg| %>
          <p class="<%= type %>"><%= msg %></p>
        <% end %>
      </div>
      <%= form.submit %>
    </div>
  <% end %>
  <div class="change-password-link"><%= link_to 'Change password', change_password_path %></div>
  

app/views/users/new.html.erb
  <%= form_with model: @user do |form| %>
    <div class="signup-form">
      <div class="input-group">
        <%= form.label :name %>
        <%= form.text_field :name, required: :required, minLength: 3 %>
        <% if @user.errors.any? %>
          <p><%= @user.errors.full_messages_for(:name).join(", ") %></p>
        <% end %>
      </div>
      <div class="input-group">
        <%= form.label :email %>
        <%= form.email_field :email, required: :required %>
        <% if @user.errors.any? %>
          <p><%= @user.errors.full_messages_for(:email).join(", ") %></p>
        <% end %>
      </div>
      <div class="input-group">
        <%= form.label :password %>
        <%= form.password_field :password, required: :required %>
      </div>
      <div class="input-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, required: :required  %>
        <% if @user.errors.any? %>
          <p><%= @user.errors.full_messages_for(:password_confirmation).join(", ") %></p>
        <% end %>
      </div>
      <%= form.submit %>
    </div>
  <% end %>